cognitive-complexity-threshold = 25
too-many-lines-threshold = 150
type-complexity-threshold = 250
single-char-binding-names-threshold = 4
trivial-copy-size-limit = 128
pass-by-value-size-limit = 256
too-many-arguments-threshold = 7
enum-variant-size-threshold = 200
verbose-bit-mask-threshold = 1
literal-representation-threshold = 10
avoid-breaking-exported-api = true
msrv = "1.70"

# Consolidated from .clippy.toml
disallowed-names = ["foo", "baz", "quux"]
suppress-restriction-lint-in-const = false

disallowed-methods = [
    "std::mem::forget",
    "std::boxed::Box::leak",
]

disallowed-types = [
    # Avoid raw pointers where safe abstractions exist
    "*const _",
    "*mut _",
]
