groups:
  # Application Health Alerts
  - name: application_health
    interval: 30s
    rules:
      - alert: ApplicationDown
        expr: up{job="codegraph-api"} == 0
        for: 15s
        labels:
          severity: critical
          service: codegraph-api
          category: availability
        annotations:
          summary: "CodeGraph API is down"
          description: "CodeGraph API has been down for more than 15 seconds"
          impact: "Complete service outage - users cannot access the API"
          remediation: "Check application logs and restart the service if necessary"

      - alert: HealthCheckFailing
        expr: health_check_status{component!=""} == 0
        for: 15s
        labels:
          severity: critical
          category: health
        annotations:
          summary: "Health check failing for {{ $labels.component }}"
          description: "Health check for {{ $labels.component }} has been failing for more than 15 seconds"
          impact: "Component {{ $labels.component }} is unhealthy"

      - alert: HighResponseTime
        expr: http_request_duration_seconds:rate5m > 2.0
        for: 30s
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "High response time detected"
          description: "HTTP request duration has exceeded 2 seconds for more than 30 seconds"
          current_value: "{{ $value }}s"

  # System Resource Alerts
  - name: system_resources
    interval: 30s
    rules:
      - alert: HighCPUUsage
        expr: system_cpu_usage_percent > 80
        for: 2m
        labels:
          severity: warning
          category: resource
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage has been above 80% for more than 2 minutes"
          current_value: "{{ $value }}%"

      - alert: CriticalCPUUsage
        expr: system_cpu_usage_percent > 95
        for: 30s
        labels:
          severity: critical
          category: resource
        annotations:
          summary: "Critical CPU usage detected"
          description: "CPU usage has been above 95% for more than 30 seconds"
          current_value: "{{ $value }}%"

      - alert: HighMemoryUsage
        expr: (system_memory_usage_bytes / (system_memory_usage_bytes + system_memory_available_bytes)) * 100 > 85
        for: 2m
        labels:
          severity: warning
          category: resource
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage has been above 85% for more than 2 minutes"
          current_value: "{{ $value }}%"

      - alert: CriticalMemoryUsage
        expr: (system_memory_usage_bytes / (system_memory_usage_bytes + system_memory_available_bytes)) * 100 > 95
        for: 30s
        labels:
          severity: critical
          category: resource
        annotations:
          summary: "Critical memory usage detected"
          description: "Memory usage has been above 95% for more than 30 seconds"
          current_value: "{{ $value }}%"

  # HTTP and API Alerts
  - name: http_alerts
    interval: 30s
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 30s
        labels:
          severity: warning
          category: errors
        annotations:
          summary: "High HTTP error rate"
          description: "HTTP error rate (5xx) is above 5% for more than 30 seconds"
          current_value: "{{ $value }}%"

      - alert: CriticalErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 10
        for: 30s
        labels:
          severity: critical
          category: errors
        annotations:
          summary: "Critical HTTP error rate"
          description: "HTTP error rate (5xx) is above 10% for more than 30 seconds"
          current_value: "{{ $value }}%"

      - alert: HighRequestLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1.0
        for: 30s
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "High request latency"
          description: "95th percentile latency is above 1 second"
          current_value: "{{ $value }}s"

      - alert: TooManyActiveRequests
        expr: http_requests_in_flight > 100
        for: 30s
        labels:
          severity: warning
          category: load
        annotations:
          summary: "Too many active requests"
          description: "Number of active HTTP requests is above 100"
          current_value: "{{ $value }}"

  # Memory Leak Detection
  - name: memory_leaks
    interval: 60s
    rules:
      - alert: MemoryLeakDetected
        expr: memscope_leaked_allocations > 0
        for: 30s
        labels:
          severity: warning
          category: memory
        annotations:
          summary: "Memory leak detected"
          description: "Memory leak detected with {{ $value }} leaked allocations"
          current_value: "{{ $value }} allocations"

      - alert: HighMemoryLeakage
        expr: memscope_leaked_memory_bytes > 100000000  # 100MB
        for: 30s
        labels:
          severity: critical
          category: memory
        annotations:
          summary: "High memory leakage detected"
          description: "Memory leakage exceeded 100MB with {{ $value }} bytes leaked"
          current_value: "{{ $value }} bytes"

      - alert: RapidMemoryGrowth
        expr: increase(memscope_active_memory_bytes[10m]) > 100000000  # 100MB in 10 minutes
        for: 30s
        labels:
          severity: warning
          category: memory
        annotations:
          summary: "Rapid memory growth detected"
          description: "Memory usage increased by more than 100MB in 10 minutes"
          current_value: "{{ $value }} bytes"

  # Database and Storage Alerts
  - name: database_alerts
    interval: 60s
    rules:
      - alert: SlowVectorSearch
        expr: histogram_quantile(0.95, rate(vector_search_duration_seconds_bucket[5m])) > 0.5
        for: 30s
        labels:
          severity: warning
          category: performance
        annotations:
          summary: "Slow vector search operations"
          description: "95th percentile vector search duration is above 500ms"
          current_value: "{{ $value }}s"

      - alert: HighParseFailureRate
        expr: rate(parse_operations_total{status="error"}[5m]) / rate(parse_operations_total[5m]) * 100 > 10
        for: 30s
        labels:
          severity: warning
          category: errors
        annotations:
          summary: "High parse failure rate"
          description: "Parse operation failure rate is above 10%"
          current_value: "{{ $value }}%"

  # Connection Pool Alerts
  - name: connection_pool
    interval: 30s
    rules:
      - alert: ConnectionPoolExhaustion
        expr: connection_pool_active / (connection_pool_active + connection_pool_idle) * 100 > 90
        for: 30s
        labels:
          severity: critical
          category: resource
        annotations:
          summary: "Connection pool near exhaustion"
          description: "Connection pool utilization is above 90%"
          current_value: "{{ $value }}%"

      - alert: NoIdleConnections
        expr: connection_pool_idle == 0 and connection_pool_active > 0
        for: 30s
        labels:
          severity: warning
          category: resource
        annotations:
          summary: "No idle connections available"
          description: "Connection pool has no idle connections available"

  # Infrastructure Monitoring
  - name: infrastructure
    interval: 60s
    rules:
      - alert: PrometheusDown
        expr: up{job="prometheus"} == 0
        for: 30s
        labels:
          severity: critical
          service: prometheus
          category: monitoring
        annotations:
          summary: "Prometheus is down"
          description: "Prometheus monitoring system is not responding"

      - alert: GrafanaDown
        expr: up{job="grafana"} == 0
        for: 30s
        labels:
          severity: warning
          service: grafana
          category: monitoring
        annotations:
          summary: "Grafana is down"
          description: "Grafana dashboard system is not responding"

      - alert: ElasticsearchDown
        expr: up{job="elasticsearch"} == 0
        for: 30s
        labels:
          severity: critical
          service: elasticsearch
          category: logging
        annotations:
          summary: "Elasticsearch is down"
          description: "Elasticsearch logging system is not responding"

  # Business Logic Alerts
  - name: business_metrics
    interval: 60s
    rules:
      - alert: LowRequestVolume
        expr: rate(http_requests_total[5m]) * 60 < 10
        for: 5m
        labels:
          severity: info
          category: business
        annotations:
          summary: "Low request volume"
          description: "Request volume is below 10 requests per minute"
          current_value: "{{ $value }} requests/min"

      - alert: NoRecentActivity
        expr: increase(http_requests_total[15m]) == 0
        for: 10m
        labels:
          severity: warning
          category: business
        annotations:
          summary: "No recent API activity"
          description: "No API requests received in the last 15 minutes"

# Recording rules for better performance
  - name: recording_rules
    interval: 30s
    rules:
      - record: http_request_duration_seconds:rate5m
        expr: rate(http_request_duration_seconds_sum[5m]) / rate(http_request_duration_seconds_count[5m])

      - record: http_requests_per_second:rate5m
        expr: rate(http_requests_total[5m])

      - record: http_error_rate:rate5m
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100

      - record: memory_utilization_percent
        expr: (system_memory_usage_bytes / (system_memory_usage_bytes + system_memory_available_bytes)) * 100