apiVersion: v1
kind: Service
metadata:
  name: codegraph-api
  labels:
    app: codegraph-api
spec:
  selector:
    app: codegraph-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  type: ClusterIP

