env = "production"

[server]
host = "0.0.0.0"
port = 8080

[rocksdb]
path = "/var/lib/codegraph/graph.db"
read_only = false

[vector]
dimension = 384
index = "ivf_flat"

[logging]
level = "info"

[security]
require_auth = true
allowed_origins = []
rate_limit_per_minute = 3000

# Secrets are expected via encrypted file or environment in production
[secrets]
openai_api_key = ""
jwt_secret = ""

