# Qwen2.5-Coder-14B-128K Configuration for CodeGraph MCP
# Model: hf.co/unsloth/Qwen2.5-Coder-14B-Instruct-128K-GGUF:Q4_K_M

[qwen_model]
# Model configuration
model_name = "qwen2.5-coder-14b-128k"
base_url = "http://localhost:11434"
context_window = 128000
max_tokens = 8192
temperature = 0.1
timeout_seconds = 90

[model_info]
# Model specifications
parameters = "14B"
quantization = "Q4_K_M"
context_length = 128000
memory_requirement = "24GB VRAM"
performance_class = "SOTA_14B"
specialization = "Code Analysis and Understanding"

[installation]
# Installation command
ollama_command = "ollama pull hf.co/unsloth/Qwen2.5-Coder-14B-Instruct-128K-GGUF:Q4_K_M"
alternative_name = "qwen2.5-coder-14b-128k"
download_size = "8.4GB"
recommended_ram = "32GB"

[capabilities]
# What Qwen2.5-Coder can do for CodeGraph
semantic_analysis = true
pattern_detection = true
architectural_understanding = true
impact_analysis = true
team_convention_analysis = true
comprehensive_codebase_analysis = true
code_quality_assessment = true

[performance_targets]
# Performance expectations
semantic_search_time = 2000      # 2 seconds for semantic search analysis
comprehensive_analysis = 5000   # 5 seconds for full codebase analysis
context_utilization = 0.8       # Use 80% of 128K context window
quality_threshold = 0.9         # 90% minimum confidence score
max_concurrent_requests = 3     # Limit concurrent requests for memory

[prompts]
# Prompt optimization settings
system_prompt_semantic = "You are Qwen2.5-Coder providing semantic code analysis for MCP-calling LLMs. Focus on understanding code purpose, patterns, and architectural context."
system_prompt_comprehensive = "You are Qwen2.5-Coder providing comprehensive codebase analysis. Use your 128K context window for complete understanding."
system_prompt_patterns = "You are Qwen2.5-Coder analyzing code patterns for consistency and quality. Provide actionable guidance for code generation."

[mcp_integration]
# MCP-specific settings
tool_prefix = "codegraph"
available_tools = [
    "semantic_intelligence",
    "enhanced_search",
    "pattern_analysis",
    "impact_assessment"
]
recommended_clients = ["claude", "gpt-4", "custom-agents"]