#!/bin/bash
# Demo: Using CodeGraph Initial Instructions

echo "═══════════════════════════════════════════════════"
echo "  CodeGraph Initial Instructions Demo"
echo "═══════════════════════════════════════════════════"
echo ""

echo "📋 Available Access Methods:"
echo ""
echo "1️⃣  Via MCP Prompt (Native Protocol)"
echo "   Request: prompts/get → codegraph_initial_instructions"
echo ""
echo "2️⃣  Via Tool Call (Simple Interface)"
echo "   Request: tools/call → read_initial_instructions"
echo ""

echo "───────────────────────────────────────────────────"
echo ""

echo "📚 What's Included:"
echo ""
echo "  🎯 Tool Selection Framework"
echo "     • Decision gates for choosing tools"
echo "     • Scope, appropriateness, evidence checks"
echo ""
echo "  🧠 Metacognitive Patterns"
echo "     • Progressive refinement"
echo "     • Evidence-driven claims"
echo "     • Impact-first changes"
echo ""
echo "  🔒 Safety Requirements"
echo "     • Impact analysis before refactoring (HARD)"
echo "     • Evidence-based reasoning (HARD)"
echo "     • Explain before execute (HARD)"
echo ""
echo "  🚀 Common Workflows"
echo "     • Implementing features"
echo "     • Debugging issues"
echo "     • Learning unfamiliar code"
echo ""

echo "───────────────────────────────────────────────────"
echo ""

echo "🎓 Quick Start for AI Agents:"
echo ""
echo "Step 1: Read the instructions"
echo "  → Call: read_initial_instructions()"
echo ""
echo "Step 2: Apply decision gates"
echo "  → Before each tool: Why this tool? What evidence?"
echo ""
echo "Step 3: Follow workflows"
echo "  → Discovery → Analysis → Impact → Implementation"
echo ""

echo "═══════════════════════════════════════════════════"
