apiVersion: v1
kind: ConfigMap
metadata:
  name: codegraph-api-config
  namespace: codegraph
  labels:
    app.kubernetes.io/name: codegraph-api
    app.kubernetes.io/part-of: codegraph
data:
  # Logging
  RUST_LOG: "codegraph_api=info,tower_http=info"

  # HTTP client pool tuning (see crates/codegraph-api/src/connection_pool.rs)
  HTTP_POOL_MAX_IDLE_PER_HOST: "64"
  HTTP_POOL_IDLE_TIMEOUT_SECS: "90"
  HTTP_CONNECT_TIMEOUT_SECS: "10"
  HTTP_TCP_KEEPALIVE_SECS: "60"
  HTTP2_KEEP_ALIVE_INTERVAL_SECS: "30"
  HTTP2_KEEP_ALIVE_TIMEOUT_SECS: "10"

  # Optional comma-separated base URLs for outbound requests used by API handlers
  OUTBOUND_BASE_URLS: ""

