apiVersion: apps/v1
kind: Deployment
metadata:
  name: codegraph-api
  namespace: codegraph
  labels:
    app.kubernetes.io/name: codegraph-api
    app.kubernetes.io/part-of: codegraph
spec:
  replicas: 3
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 25%
  minReadySeconds: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: codegraph-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: codegraph-api
        app.kubernetes.io/part-of: codegraph
    spec:
      serviceAccountName: codegraph-api
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: codegraph-api
          # TODO: set your published image
          image: ghcr.io/your-org/codegraph-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: codegraph-api-config
                  key: RUST_LOG
            - name: HTTP_POOL_MAX_IDLE_PER_HOST
              valueFrom:
                configMapKeyRef:
                  name: codegraph-api-config
                  key: HTTP_POOL_MAX_IDLE_PER_HOST
            - name: HTTP_POOL_IDLE_TIMEOUT_SECS
              valueFrom:
                configMapKeyRef:
                  name: codegraph-api-config
                  key: HTTP_POOL_IDLE_TIMEOUT_SECS
            - name: HTTP_CONNECT_TIMEOUT_SECS
              valueFrom:
                configMapKeyRef:
                  name: codegraph-api-config
                  key: HTTP_CONNECT_TIMEOUT_SECS
            - name: HTTP_TCP_KEEPALIVE_SECS
              valueFrom:
                configMapKeyRef:
                  name: codegraph-api-config
                  key: HTTP_TCP_KEEPALIVE_SECS
            - name: HTTP2_KEEP_ALIVE_INTERVAL_SECS
              valueFrom:
                configMapKeyRef:
                  name: codegraph-api-config
                  key: HTTP2_KEEP_ALIVE_INTERVAL_SECS
            - name: HTTP2_KEEP_ALIVE_TIMEOUT_SECS
              valueFrom:
                configMapKeyRef:
                  name: codegraph-api-config
                  key: HTTP2_KEEP_ALIVE_TIMEOUT_SECS
            - name: OUTBOUND_BASE_URLS
              valueFrom:
                configMapKeyRef:
                  name: codegraph-api-config
                  key: OUTBOUND_BASE_URLS
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: codegraph-api-secrets
                  key: OPENAI_API_KEY
                  optional: true
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
            timeoutSeconds: 2
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values: ["codegraph-api"]
                topologyKey: kubernetes.io/hostname
